name: testing Caesar cipher # Name of the Ci

on: [push] # When to run the CI

jobs:
  test: # Name of job
    name: Test on ubuntu with python 3.9
    runs-on: ubuntu-latest # OS to run on

    steps:
      - uses: actions/checkout@v2 # Pre-made action to check out repo
      - name: Set up Python
        uses: actions/setup-python@v2 # Pre-made action to set up python
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install pip --upgrade
          python -m pip install pytest pytest-cov
      - name: Test with pytest
        run: |
          python -m pytest test_caesar_cipher.py --cov=caesar_cipher --cov-report term-missing
